swagger: '2.0'
info:
  description: API Clients
  version: '1.0'
  title: Clients
  contact:
    name: Leonardo Borchartt
  license:
    name: Apache Licence Version 2.0
    url: 'https://apache.org'
host: 'localhost:8083'
basePath: /
tags:
  - name: clients-controller
    description: Clients Controller
paths:
  /api/v1/clients:
    post:
      tags:
        - clients-controller
      summary: Create a client.
      operationId: postUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: client
          description: client
          required: true
          schema:
            $ref: '#/definitions/Client'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/ClientDto'
        '400':
          description: Bad Request
  /api/v1/clients/name:
    get:
      tags:
        - clients-controller
      summary: Find clients by name.
      operationId: searchUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: name
          in: query
          description: name
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ClientDto'
        '404':
          description: Not Found
  '/api/v1/clients/{id}':
    get:
      tags:
        - clients-controller
      summary: Find client by Id.
      operationId: getIdUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ClientDto'
        '400':
          description: Bad Request
        '404':
          description: Not Found
    put:
      tags:
        - clients-controller
      summary: Update a existing client.
      operationId: changeClientNameUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - in: body
          name: name
          description: name
          required: true
          schema:
            properties:
              name:
                type: string
                example: "Leonardo Borchartt"

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ClientDto'
        '400':
          description: Bad Request
        '404':
          description: Not Found
    delete:
      tags:
        - clients-controller
      summary: Delete a client.
      operationId: deleteUsingDELETE
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
definitions:
  Client:
    type: object
    properties:
      birthday:
        type: string
        format: date
        example: "1993-10-09"
      city:
        type: string
        example: "Floripa"
      gender:
        type: string
        example: "M"
      name:
        type: string
        example: "Leonardo Borchartt"
  ClientDto:
    type: object
    properties:
      id:
        type: Long
        example: 1
      name:
        type: string
        example: "Leonardo Borchartt"
      city:
        type: string
        example: "Floripa"
      gender:
        type: string
        example: "M"
      birthday:
        type: LocalDate
        format: date
        example: "1993-10-09"
      age:
        type: integer
        format: date
        example: 26

