server:
  port: 8084
spring:
  datasource:
    initialization-mode: always
    password: root
    url: jdbc:mysql://localhost:3306/city?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true



logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


